@startuml Board ERD

entity kb_user { 
    * user_no : SERIAL <<generated>>
    --
    user_id : VARCHAR(30) NOT NULL
    password : VARCHAR(30) NOT NULL
    username : VARCHAR(30) NOT NULL
    created_date : TIMESTAMP NOT NULL
}

entity kb_post {
    * post_no : SERIAL <<generated>>
    --
    * user_no : INTEGER <<FK>>
    category : VARCHAR(30) NULL
    title : VARCHAR(100) NOT NULL
    content : TEXT NULL
    created_date : TIMESTAMP NOT NULL
    up : INT NOT NULL
    down : INT NOT NULL
}

entity kb_comment {
    * comment_no : SERIAL <<generated>>
    --
    * user_no : INTEGER <<FK>>
    * post_no : INTEGER <<FK>>
    content TEXT NOT NULL
    created_date TIMESTAMP NOT NULL
    up INT NOT NULL
    down INT NOT NULL
}

kb_user ||--o{ kb_post
kb_post ||--o{ kb_comment
kb_user ||--o{ kb_comment

@enduml